version: '3.9'
services:
  # Node App
  app:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo-rs
  # Mongo Service
  # mongo:
  #   image: mongo:4
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: docker
  #     MONGO_INITDB_ROOT_PASSWORD: docker
  #     MONGO_INITDB_DATABASE: authdb
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - app-net
  mongo-rs:
    build: ./mongodb_rs
    container_name: mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_HOST: localhost
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
volumes:
  mongodb_data:
