version: '3.9'
services:
  # Node App
  app:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  # Mongo Service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGO_DATA_DIR=/data/db
      - MONGODB_REPLICA_SET_KEY=WXgvaSGf
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-net
    

networks:
  app-net:
    driver: bridge
volumes:
  mongodb_data:
